-- Criar o banco de dados (opcional, remova os comentários caso queira usar)
-- CREATE DATABASE IF NOT EXISTS bd_adoracao;
-- USE bd_adoracao;

-- =========================================
-- TABELAS SEM CHAVES ESTRANGEIRAS (PARENTES)
-- =========================================

CREATE TABLE PAIS (
    ID_PAIS INT NOT NULL AUTO_INCREMENT,
    SIGLA_PAIS VARCHAR(2),
    NOME_PAIS VARCHAR(40),
    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE SITUACAO (
    ID_SITUACAO DECIMAL(10,0) NOT NULL,
    DESC_SITUACAO VARCHAR(20),
    PRIMARY KEY (ID_SITUACAO)
);

CREATE TABLE TIPO_COLABORADOR (
    ID_TIPO_COLABORADOR INT NOT NULL AUTO_INCREMENT,
    DESC_TIPO_COLABORADOR VARCHAR(20),
    PRIMARY KEY (ID_TIPO_COLABORADOR)
);

CREATE TABLE FUNCOES (
    ID_FUNCAO INT NOT NULL AUTO_INCREMENT,
    DESCRICAO_FUNCAO VARCHAR(20),
    ORDEM_FUNCAO INT,
    IMAGEM VARCHAR(10),
    PRIMARY KEY (ID_FUNCAO)
);

CREATE TABLE TIPO_ATIVIDADE (
    ID_ATIVIDADE INT NOT NULL AUTO_INCREMENT,
    DESC_ATIVIDADE VARCHAR(30),
    PRIMARY KEY (ID_ATIVIDADE)
);

CREATE TABLE FORMA_ATIVIDADE (
    ID_FORMA_ATIVIDADE INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_FORMA_ATIVIDADE)
);

CREATE TABLE TREINAMENTO (
    ID_TREINAMENTO INT NOT NULL AUTO_INCREMENT,
    FORMA_TREINAMENTO CHAR(1),
    DESC_TREINAMENTO VARCHAR(100),
    OBS_TREINAMENTO VARCHAR(200),
    DATA_INCLUSAO DATETIME,
    DATA_ATUALIZACAO DATETIME,
    COLABORADOR_ATUALIZOU CHAR(10),
    PRIMARY KEY (ID_TREINAMENTO)
);

-- =========================================
-- TABELAS DEPENDENTES (NÍVEL 1)
-- =========================================

CREATE TABLE ESTADO (
    ID_ESTADO INT NOT NULL AUTO_INCREMENT,
    ID_PAIS INT NOT NULL,
    NOME_ESTADO VARCHAR(40),
    SIGLA_ESTADO VARCHAR(5),
    PRIMARY KEY (ID_ESTADO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE REGIONAL (
    ID_REGIONAL INT NOT NULL AUTO_INCREMENT,
    ID_PAIS INT NOT NULL,
    DESC_REGIONAL VARCHAR(20),
    PRIMARY KEY (ID_REGIONAL),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

-- =========================================
-- TABELAS DEPENDENTES (NÍVEL 2)
-- =========================================

CREATE TABLE REGIONAL_ESTADO (
    ID_PAIS INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    ID_REGIONAL INT NOT NULL,
    PRIMARY KEY (ID_PAIS, ID_ESTADO, ID_REGIONAL),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    FOREIGN KEY (ID_REGIONAL) REFERENCES REGIONAL(ID_REGIONAL)
);

CREATE TABLE ARQUIDIOCESE (
    ID_ARQUIDIOCESE INT NOT NULL AUTO_INCREMENT,
    ID_ESTADO INT NOT NULL,
    ID_SITUACAO DECIMAL(10,0) NOT NULL,
    NOME_ARQUIDIOCESE VARCHAR(50),
    UF_ARQUIDIOCESE CHAR(2),
    IDENTIFICA_FOTO DECIMAL(10,0),
    PRIMARY KEY (ID_ARQUIDIOCESE),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
    FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO(ID_SITUACAO)
);

-- =========================================
-- TABELAS DEPENDENTES (NÍVEL 3)
-- =========================================

CREATE TABLE HISTORICO_ARQUIDIOCESE (
    ID_HISTORICO INT NOT NULL AUTO_INCREMENT,
    ID_ARQUIDIOCESE INT NOT NULL,
    DT_HISTORICO DATETIME,
    DESCRICAO_HISTORICO VARCHAR(250),
    PRIMARY KEY (ID_HISTORICO),
    FOREIGN KEY (ID_ARQUIDIOCESE) REFERENCES ARQUIDIOCESE(ID_ARQUIDIOCESE)
);

CREATE TABLE PAROQUIA (
    ID_PAROQUIA INT NOT NULL AUTO_INCREMENT,
    ID_REGIONAL INT NOT NULL,
    ID_ARQUIDIOCESE INT NOT NULL,
    ID_ESTADO INT,
    ID_COORDENADOR INT,
    NOME_PAROQUIA VARCHAR(50),
    PAROCO_PAROQUIA VARCHAR(50),
    ENDERECO_PAROQUIA VARCHAR(50),
    BAIRRO_PAROQUIA VARCHAR(30),
    CIDADE_PAROQUIA VARCHAR(40),
    GPS_LATITUDE FLOAT,
    GPS_LONGITUDE FLOAT,
    TIPO_PAROQUIA INT,
    FOTO_PAROQUIA BIT,
    PRIMARY KEY (ID_PAROQUIA),
    FOREIGN KEY (ID_REGIONAL) REFERENCES REGIONAL(ID_REGIONAL),
    FOREIGN KEY (ID_ARQUIDIOCESE) REFERENCES ARQUIDIOCESE(ID_ARQUIDIOCESE),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- =========================================
-- TABELAS DEPENDENTES (NÍVEL 4)
-- =========================================

CREATE TABLE COLABORADOR (
    ID_COLABORADOR INT NOT NULL AUTO_INCREMENT,
    ID_PAROQUIA INT NOT NULL,
    ID_TIPO_COLABORADOR INT,
    NOME_COLABORADOR VARCHAR(50),
    APELIDO_COLABORADOR VARCHAR(15),
    SEXO CHAR(1),
    DT_NASC_COLABORADOR DATETIME,
    TEL_COLABORADOR VARCHAR(15),
    EMAIL_COLABORADOR VARCHAR(50),
    STATUS_COLABORADOR CHAR(1),
    SENHA_COLABORADOR VARCHAR(40),
    CPF_COLABORADOR DECIMAL(11,0),
    TALENTO_COLABORADOR VARCHAR(1000),
    FOTO_COLABORADOR LONGBLOB,
    DATA_ATUALIZACAO DATETIME,
    PRIMARY KEY (ID_COLABORADOR),
    FOREIGN KEY (ID_PAROQUIA) REFERENCES PAROQUIA(ID_PAROQUIA),
    FOREIGN KEY (ID_TIPO_COLABORADOR) REFERENCES TIPO_COLABORADOR(ID_TIPO_COLABORADOR)
);

-- =========================================
-- TABELAS DE LIGAÇÃO E DEPENDENTES DE COLABORADOR
-- =========================================

CREATE TABLE ACESSOS_COLABORADOR (
    ID_COLABORADOR INT NOT NULL,
    ID_FUNCAO INT NOT NULL,
    TIPO_ACESSO CHAR(2),
    PRIMARY KEY (ID_COLABORADOR, ID_FUNCAO),
    FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR(ID_COLABORADOR),
    FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCOES(ID_FUNCAO)
);

CREATE TABLE TREINAMENTO_COLABORADOR (
    ID_COLABORADOR INT NOT NULL,
    ID_TREINAMENTO INT NOT NULL,
    STATUS_TREINAMENTO CHAR(1),
    PRIMARY KEY (ID_COLABORADOR, ID_TREINAMENTO),
    FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR(ID_COLABORADOR),
    FOREIGN KEY (ID_TREINAMENTO) REFERENCES TREINAMENTO(ID_TREINAMENTO)
);

CREATE TABLE DIAS_TREINAMENTO (
    ID_TREINAMENTO INT NOT NULL,
    ID_COLABORADOR INT,
    DT_TREINAMENTO DATE,
    HORA_INICIO DATETIME,
    HORA_FIM DATETIME,
    PRIMARY KEY (ID_TREINAMENTO, DT_TREINAMENTO),
    FOREIGN KEY (ID_TREINAMENTO) REFERENCES TREINAMENTO(ID_TREINAMENTO),
    FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR(ID_COLABORADOR)
);
