server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location = /newsite {
        return 301 /newsite/;
    }

    location /newsite/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /usr/share/nginx/html/index.html;
    }
}
